### ISSUE TITLE
License for corporate use

### ISSUE THREAD

**Issue by thysce** [jaem3l/unfuck#1]
Hey 👋🏻. Nice fuckery. Can you please add a license, so that I can use this in my multi-billion-dollar corporate codebase as a dependency?
Would be awesome to get rid of some of the burdensome, so called „good design“ ;)

**Comment by chr-hertel** [comment]
Pretty happy to provide this to you with MIT license
https://github.com/jaem3l/unfuck/releases/tag/v0.1.1

I want to point out ...
![Bildschirmfoto von 2022-02-22 15-16-53](https://user-images.githubusercontent.com/2852185/155150770-492f8df3-2ea6-422e-9189-8adbee1051b6.png)

sorry
