### ISSUE TITLE
example in the readme should be fixed  (lol)

### ISSUE THREAD

**Issue by mvit777** [jaem3l/unfuck#3]
final class Example
{
    private string $foo;

    public function __construct(string $foo)
    {
        $this->foo = $foo;
    }
   //no vendor library would ever mark this method private
 //such a mistake makes your library look less needed (so to speak)
    private function getFoo(): string
    {
        return $this->foo;
    }
}

**Comment by chr-hertel** [comment]
Well, I agree that this example class doesn't have any real world use case, but as it is just used to demostrate what `unfuck` can do for you, this should be sufficient :)

**Comment by mvit777** [comment]
>it is just used to demostrate what unfuck can do for you, this should be sufficient :)

thnx for fixing it
